In [3]:

#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


In [20]:
# Question2

#What are the numpy datatypes for the car,mpg, horsepower and origin arrays? (Hint: Not type(car) and use print() to print the numpy type.)
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)



object
float64
float64
object


In [38]:
# Question4

#Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code.
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
print(displacement.ndim)
print(horsepower.ndim) 
print(weight.ndim)
print(acceleration.ndim) 
print(model.ndim)
print(origin.ndim) 

1
1
1
1
1
1
1
1
1


In [43]:
#Quesion 5.

#Show how to:

#multiply the mpg array by 12.
#divide the mpg array by 3.
#raise the mpg array to the power of 4.
#take the square root of the mpg array.


np.multiply(mpg,12)
np.divide(mpg,3)
print(mpg**4)
np.sqrt(mpg)

[ 104976.       50625.      104976.       65536.       83521.
   50625.       38416.       38416.       38416.       50625.
       0.           0.           0.           0.           0.
   50625.       38416.           0.       50625.       38416.
  331776.      234256.      104976.      194481.      531441.
  456976.      390625.      331776.      390625.      456976.
  194481.       10000.       10000.       14641.        6561.
  531441.      614656.      390625.      390625.           0.
  130321.       65536.       83521.      130321.      104976.
   38416.       38416.       38416.       38416.       20736.
   28561.       28561.      104976.      234256.      130321.
  104976.      279841.      614656.      810000.      810000.
  923521.     1500625.      531441.      456976.      331776.
  390625.      279841.      160000.      194481.       28561.
   38416.       50625.       38416.       83521.       14641.
   28561.       20736.       28561.      130321.       50625.
   28561

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

In [50]:
#Quesion 9

#Select the last element in each subarray (do this with one operation.)

select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

select_more[0:,2]
# returns array([3, 6, 9])

array([3, 6, 9])

In [63]:
#question 12

#Create a 2D array and print its shape as well as ndim. (Any shape is fine)

#Create a 3D array and print its shape as well as ndim.

#Create a 4D array and print its shape as well as ndim. It's hard to visualize 4-Dimensions but numpy can do it with ease


import numpy as np

a = np.array([[1,3,5,6],[3,4,5,2]])
print(a.shape)
print(a.ndim)



b = np.array([[[3,5,4],[6,5,4],[3,4,5]]])
print(b.shape)
print(b.ndim)


c = np.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
print(c.shape)
print(c.ndim)

(2, 4)
2
(1, 3, 3)
3
(1, 1, 4, 4)
4


In [ ]:
#Quesion15

#Why might you prefer an np.array() over a Python list? And when is a Python list preferred?

numpy array and list are almost the same but numpy array more powerful than list 
consumes less memory.
fast as compared to the python List.
convenient to use.
when we will preferred to use list???????????

In [64]:
#Question16

#What is an identity matrix? Create an identiy matrix of size 5 using an np method.

import numpy as np
dimension = int(input("enter the dimension of identitiy matrix: "))
identity_matrix = np.identity(dimension,dtype = "int")
print(identity_matrix)











enter the dimension of identitiy matrix: 5
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [66]:
#Quesion17.

#Transpose the following array.

transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(transpose_me.transpose(1,0))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [73]:
#Quesion10

#Use the built-in np.lookfor() function to search for 'log'.

#Use the function you find and apply it to mpg.
#np.lookfor("log")
a = np.log(mpg)
print(a)

[2.89037176 2.7080502  2.89037176 2.77258872 2.83321334 2.7080502
 2.63905733 2.63905733 2.63905733 2.7080502        -inf       -inf
       -inf       -inf       -inf 2.7080502  2.63905733       -inf
 2.7080502  2.63905733 3.17805383 3.09104245 2.89037176 3.04452244
 3.29583687 3.25809654 3.21887582 3.17805383 3.21887582 3.25809654
 3.04452244 2.30258509 2.30258509 2.39789527 2.19722458 3.29583687
 3.33220451 3.21887582 3.21887582       -inf 2.94443898 2.77258872
 2.83321334 2.94443898 2.89037176 2.63905733 2.63905733 2.63905733
 2.63905733 2.48490665 2.56494936 2.56494936 2.89037176 3.09104245
 2.94443898 2.89037176 3.13549422 3.33220451 3.40119738 3.40119738
 3.4339872  3.55534806 3.29583687 3.25809654 3.17805383 3.21887582
 3.13549422 2.99573227 3.04452244 2.56494936 2.63905733 2.7080502
 2.63905733 2.83321334 2.39789527 2.56494936 2.48490665 2.56494936
 2.94443898 2.7080502  2.56494936 2.56494936 2.63905733 2.89037176
 3.09104245 3.04452244 3.25809654 3.09104245 3.33220451 3.135494

C:\Users\12674\AppData\Local\Temp/ipykernel_13948/3510624138.py:6: RuntimeWarning: divide by zero encountered in log
  a = np.log(mpg)


In [74]:
#Quesion 11
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

In [80]:
# Question 13. 
# Use boolean indexing to create an array of True/False using origin and the value 'US'.
boolean_index = origin == "US"
print (boolean_index)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

In [92]:
# Question 14.
# Apply your index (from above) to the car array. You should now only see cars that are of US origin.
boolean_index = []
for i in range(len(df)):
    if origin[i] == "US":
        boolean_index.append(car[i])
print(boolean_index)

['Chevrolet Chevelle Malibu', 'Buick Skylark 320', 'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino', 'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii', 'Pontiac Catalina', 'AMC Ambassador DPL', 'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)', 'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)', 'Dodge Challenger SE', "Plymouth 'Cuda 340", 'Ford Mustang Boss 302', 'Chevrolet Monte Carlo', 'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet', 'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20', 'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto', 'AMC Gremlin', 'Plymouth Satellite Custom', 'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador', 'Chevrolet Impala', 'Pontiac Catalina Brougham', 'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)', 'Ford Country Squire (sw)', 'Pontiac Safari (sw)', 'AMC Hornet Sportabout (sw)', 'Chevrolet Vega (sw)', 'Pontiac Firebird', 'Ford Mustang', 'Mercury Capri 2000', 'Plymouth Cricket', 'Dodge Colt

In [ ]:
#Quesion3.
#numpy is often imported as np. What is this action called? Why might you do this?

#Answer: np is short version of numpy and np version more convenient.

In [107]:
#Quesion6.

#What is the ___ of horsepower?

#sum
#min
#max
#median
#Optional: mode (May need to google help)
    
   

b = sum(horsepower)
print(b)
    
    
min = np.min(horsepower)
print(min)

max = np.max(horsepower)
print(max)


madian = np.median(horsepower)
print(madian)

42033.0
0.0
230.0
93.5


In [116]:
#Quesion7.
#Select a subset of acceleration.

#Select only the first 5 elements.
#Select every other element (new selection).

print(df.head(5))


print(df.loc[:])

                         Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1          Buick Skylark 320  15.0          8         350.0       165.0   
2         Plymouth Satellite  18.0          8         318.0       150.0   
3              AMC Rebel SST  16.0          8         304.0       150.0   
4                Ford Torino  17.0          8         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0     70     US  
1  3693.0          11.5     70     US  
2  3436.0          11.0     70     US  
3  3433.0          12.0     70     US  
4  3449.0          10.5     70     US  
                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3

In [117]:
#Quesion 8
#Show how to select the number 99 in the array below.


select_99 = np.array([[1,2,3],
                      [4,5,99]])
select_99[1:,2]

array([99])

In [119]:
#Quesion1 
#How can you get help on np.array?
#Call dir() on np.array.

#Call dir() on car.

#Note the difference. car has methods and attributes we can use.

dir(np.array)




dir (car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__